#!/bin/sh
# [Gedit Tool]
# Name=Run
# Shortcut=<Primary>r
# Languages=
# Applicability=local
# Output=output-panel
# Input=document
# Save-files=document


export PATH=$HOME/local/bin:$PATH

if [ "$(echo $GEDIT_CURRENT_DOCUMENT_NAME | grep '\.coffee$')" ]; then
  coffee $GEDIT_CURRENT_DOCUMENT_NAME
elif [ "$(echo $GEDIT_CURRENT_DOCUMENT_NAME | grep '\.js$')" ]; then
  node $GEDIT_CURRENT_DOCUMENT_NAME
elif [ "$(echo $GEDIT_CURRENT_DOCUMENT_NAME | grep '\.py$')" ]; then
  python $GEDIT_CURRENT_DOCUMENT_NAME
elif [ "$(echo $GEDIT_CURRENT_DOCUMENT_NAME | grep '\.rb$')" ]; then
  ruby $GEDIT_CURRENT_DOCUMENT_NAME
else
  echo "I do not know how to run ${GEDIT_CURRENT_DOCUMENT_NAME}"
fi
