#!/bin/sh
# [Gedit Tool]
# Name=Run Python
# Shortcut=<Primary>r
# Languages=python
# Applicability=local
# Output=output-panel
# Input=document
# Save-files=document

python $GEDIT_CURRENT_DOCUMENT_NAME
